export default {
  SET_CLIENTS   : "TWITTER_CLIENT_SET_CLIENTS",
  CREATE_CLIENT : "TWITTER_CLIENT_CREATE_CLIENT",
  UPDATE_CLIENT : "TWITTER_CLIENT_UPDATE_CLIENT",
  DELETE_CLIENT : "TWITTER_CLIENT_DELETE_CLIENT",
};
